version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: oy2gd2btwyk3ejzkntgaoe3sd2xyoi4uvklpvemwirn4bm
  skip_symbols: true